# _target_: pytorch_lightning.Trainer
#
# gpus: 1
#
# min_epochs: 1
# max_epochs: 100
# enable_model_summary: False   # Use `Trainer.Callbacks` instead.

_target_: pytorch_lightning.Trainer

default_root_dir: ${paths.output_dir}

min_epochs: 1 # prevents early stopping
max_epochs: 100


accelerator: cpu
devices: 1

# mixed precision for extra speed-up
# precision: 16

# gradient_clip_val: 1000.

# how often to check the validation set, validating after N batches
# val_check_interval: 2000

# perform a validation loop every N training epochs
check_val_every_n_epoch: 1

# set True to to ensure deterministic results
# makes training slower but gives more reproducibility than just setting seeds
deterministic: False

# Enable anomaly detection for the autograd engine
detect_anomaly: False
