_target_: models.AugmentationBased
img_shape: ${img_shape}
msg_len: ${msg_len}
# a value in ['DA', 'ForwardASL', 'StandardASL']
method: ForwardASL

train_distortions:
  # resize:
  #   _target_: models.noiser.RandomResizeAndBack
  #   ratio: [0.5, 0.5]
  # GaussianBlur:
  #   _target_: kornia.augmentation.RandomGaussianBlur
  #   kernel_size: [3, 3]
  #   sigma: [0.1, 1.0]
  #   p: 1.
  # RandomVerticalFlip:
  #   _target_: kornia.augmentation.RandomVerticalFlip
  #   p: 0.5
  # RandomHorizontalFlip:
  #   _target_: kornia.augmentation.RandomHorizontalFlip
  #   p: 0.5
  RandomRotation:
    _target_: kornia.augmentation.RandomRotation
    degrees: 10
    p: 1.0

test_distortions:
  # resize03:
  #   _target_: models.noiser.RandomResizeAndBack
  #   ratio: [0.3, 0.3]
  # resize04:
  #   _target_: models.noiser.RandomResizeAndBack
  #   ratio: [0.4, 0.4]
  # resize05:
  #   _target_: models.noiser.RandomResizeAndBack
  #   ratio: [0.5, 0.5]
  # resize06:
  #   _target_: models.noiser.RandomResizeAndBack
  #   ratio: [0.6, 0.6]
  # resize07:
  #   _target_: models.noiser.RandomResizeAndBack
  #   ratio: [0.7, 0.7]
  # resize08:
  #   _target_: models.noiser.RandomResizeAndBack
  #   ratio: [0.8, 0.8]
  # resize09:
  #   _target_: models.noiser.RandomResizeAndBack
  #   ratio: [0.9, 0.9]
  # resize10:
  #   _target_: models.noiser.RandomResizeAndBack
  #   ratio: [1.0, 1.0]
  # resize11:
  #   _target_: models.noiser.RandomResizeAndBack
  #   ratio: [1.1, 1.1]
  # resize12:
  #   _target_: models.noiser.RandomResizeAndBack
  #   ratio: [1.2, 1.2]
  # resize13:
  #   _target_: models.noiser.RandomResizeAndBack
  #   ratio: [1.3, 1.3]
  # resize14:
  #   _target_: models.noiser.RandomResizeAndBack
  #   ratio: [1.4, 1.4]
  # resize15:
  #   _target_: models.noiser.RandomResizeAndBack
  #   ratio: [1.5, 1.5]
  # resize:
  #   _target_: models.noiser.RandomResizeAndBack
  #   ratio: [0.5, 1.5]
  # GaussianBlur01:
  #   _target_: kornia.augmentation.RandomGaussianBlur
  #   kernel_size: [3, 3]
  #   sigma: [0.1, 1.0]
  #   p: 1.
  # GaussianBlur02:
  #   _target_: kornia.augmentation.RandomGaussianBlur
  #   kernel_size: [3, 3]
  #   sigma: [1., 2.0]
  #   p: 1.
  # GaussianBlur03:
  #   _target_: kornia.augmentation.RandomGaussianBlur
  #   kernel_size: [5, 5]
  #   sigma: [0.1, 1.0]
  #   p: 1.
  # GaussianBlur04:
  #   _target_: kornia.augmentation.RandomGaussianBlur
  #   kernel_size: [5, 5]
  #   sigma: [1., 2.0]
  #   p: 1.
  # GaussianBlur05:
  #   _target_: kornia.augmentation.RandomGaussianBlur
  #   kernel_size: [7, 7]
  #   sigma: [0.1, 1.0]
  #   p: 1.
  # GaussianBlur06:
  #   _target_: kornia.augmentation.RandomGaussianBlur
  #   kernel_size: [7, 7]
  #   sigma: [1., 2.0]
  #   p: 1.
  # RandomVerticalFlip:
  #   _target_: kornia.augmentation.RandomVerticalFlip
  #   p: 0.5
  # RandomHorizontalFlip:
  #   _target_: kornia.augmentation.RandomHorizontalFlip
  #   p: 0.5
  RandomRotation15:
    _target_: kornia.augmentation.RandomRotation
    degrees: 10
    p: 1.
  RandomRotation20:
    _target_: kornia.augmentation.RandomRotation
    degrees: 15
    p: 1.
  RandomRotation30:
    _target_: kornia.augmentation.RandomRotation
    degrees: 20
    p: 1.

loss_cfg:
  l1_loss_scale: 1.5
  msg_loss_scale: 1.
  gan_loss_scale: 1.

lr: 0.0001
