model_checkpoint:
  _target_: pytorch_lightning.callbacks.ModelCheckpoint
  dirpath: ${paths.output_dir}/checkpoints
  save_top_k: -1
  every_n_epochs: 30

# early_stopping:
#   _target_: pytorch_lightning.callbacks.EarlyStopping
#   monitor: "val/acc" # name of the logged metric which determines when model is improving
#   mode: "max" # "max" means higher metric value is better, can be also "min"
#   patience: 100 # how many validation epochs of not improving until training stops
#   min_delta: 0 # minimum change in the monitored metric needed to qualify as an improvement

model_summary:
  _target_: pytorch_lightning.callbacks.ModelSummary
  max_depth: 5

progress_bar:
  _target_: pytorch_lightning.callbacks.TQDMProgressBar
