_target_: datamodules.datamodule.DataModule
dataset:
  _target_: datamodules.host_distortion_pair.HostDistortionPair
  _partial_: true
  host_dir: ${paths.data_dir}/mirflickr/
  distortion_dataset:
    _target_: datamodules.distortion_pair.DistortionPair
    data_root: ${paths.data_dir}/ImageTranslationPair/
    distortion_dir: jpeg/qf=50
    img_shape: [3, 128, 128]
    train_valid_test_nums: [1000, 10, 10]
  img_shape: ${img_shape}
  secret_len: ${msg_len}

dataloader_cfg:
  batch_size: 32
  num_workers: 4
  pin_memory: true
  # drop_last: true
